# Generated by Django 2.0.2 on 2018-03-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_name', models.CharField(max_length=255)),
                ('module_num', models.CharField(choices=[('1', 'Module 1'), ('2', 'Module 2'), ('3', 'Module 3')], default='1', max_length=1)),
            ],
        ),
    ]
